apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
      - name: sentiment-analysis
        image: your-dockerhub-username/sentiment-analysis:latest
        ports:
        - containerPort: 5000
